### ISSUE TITLE
no internet access in clients

### ISSUE THREAD

**Issue by malikshi** [cenk1cenk2/docker-softether-vpnsrv#17]
hi set-up docker like this
>docker create \
--name=softether-vpnsrv \
-e TZ=Asia/Jakarta \
-e SRVIPSUBNET=10.255.0 \
-e SRVIPNETMASK=255.255.255.0 \
-p 110:110/tcp \
-p 992:992/tcp \
-p 5555:5555/tcp \
-p 1194:1194/udp \
-p 25000:25000/udp \
-p 500:500/udp \
-p 4500:4500/udp \
-p 1701:1701/tcp \
-v $PWD/cfg/vpn_server.config:/cfg/vpn_server.config \
-v $PWD/cfg/dnsmasq.conf:/cfg/dnsmasq.conf \
-v /etc/letsencrypt/:/etc/letsencrypt/ \
-v /etc/ssl/:/etc/ssl/ \
--restart unless-stopped \
--privileged \
cenk1cenk2/softether-vpnsrv:latest

then setting hub and importing letsencrypt certs. there is trouble after I set the whole thing in server, clients can't connect or get assign IP from server. and trying reboot server then login softether manager(server) in windows and all the setting removed, just what happened, did I miss something?

**Comment by malikshi** [comment]
solved:
no need to add 
>-v $PWD/cfg/vpn_server.config:/cfg/vpn_server.config
-v $PWD/cfg/dnsmasq.conf:/cfg/dnsmasq.conf

if using vpncmd to setting up a server

**Comment by malikshi** [comment]
still need help docker cp

**Comment by malikshi** [comment]
All done

**Comment by cenk1cenk2** [comment]
To make stuff persistent you should make a persistent volume for config. If nothing is found it will create that configuration.

```bash
docker create
--name=softether-vpnsrv
-e TZ=Asia/Jakarta
-e SRVIPSUBNET=10.255.0
-e SRVIPNETMASK=255.255.255.0
-p 110:110/tcp
-p 992:992/tcp
-p 5555:5555/tcp
-p 1194:1194/udp
-p 25000:25000/udp
-p 500:500/udp
-p 4500:4500/udp
-p 1701:1701/tcp
-v $PWD/cfg/:/cfg/
-v /etc/letsencrypt/:/etc/letsencrypt/
-v /etc/ssl/:/etc/ssl/
--restart unless-stopped
--privileged
cenk1cenk2/softether-vpnsrv:latest
```

This would be more useful in the docker setup, so you dont have to copy paste stuff each time. But it is advised that you use a docker-compose specification.

**Comment by malikshi** [comment]
I'm too newb for docker. Thank you for the advice.
