### ISSUE TITLE
old router can't connected to l2tp

### ISSUE THREAD

**Issue by malikshi** [cenk1cenk2/docker-softether-vpnsrv#18]
can't use old cipher `DHE-RSA-AES256-SHA` cause the old router can't connect l2tp.
then compare to RTM build 17 august with that cipher it's work fine. is it related to a different softether version?

**Comment by malikshi** [comment]
the latest version from softethervpn 5.02.5180 and your docker still 5.0.1.9674 isn't updated properly?

**Comment by malikshi** [comment]
found the answer Softether GitHub version remove sslv3 completely. back to RTM version

**Comment by cenk1cenk2** [comment]
Hello @malikshi ,

There was an issue on the main repository, that is why it tagged it as 5.02.5180 but did not build and push it properly. The issue can be seen [here](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1439). I will give it another try whenever this issue is closed.

**Comment by cenk1cenk2** [comment]
![image](https://user-images.githubusercontent.com/26881592/131386511-41f48364-e6b8-488b-9d77-b7a38cfd9fca.png)

It's currently still the same. If any update is done on the issue I will immediately try it again.

**Comment by malikshi** [comment]
sir can you confirm this commit [1534](https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1534) fixed the problem.

**Comment by cenk1cenk2** [comment]
Hey @malikshi ,

I do not know it would be tagged soon, so what I have decided to not keep you waiting is to create an edge tag that would build the master branch of the `softether` repository.

**Comment by malikshi** [comment]
> so what I have decided to not keep you waiting is to create an edge tag that would build the master branch of the softether repository.

Sorry for the trouble 🙏.
i had running one vps running with rtm because the problem with bridge between docker and rtm version makes client can't connect/ to vpn, i also had your docker version seem works fine along with other containers and client can connected to internet without problem arise( just old router can't connect to it)

**Comment by cenk1cenk2** [comment]
Na it's no trouble, please do not say it like that.

Can you please give a try to the `edge` tag, it should build the current master which has the fixes you require and fixes for the build issues on Alpine Linux.

If you can give me feedback whenever you are able to try it out, I can also update the VPN-client with the same methodology.

**Comment by malikshi** [comment]
i having problem with openvpn protocol udp.
```
2022-01-16 12:20:27 read UDP: Unknown error (code=10054)
2022-01-16 12:20:29 read UDP: Unknown error (code=10054)
2022-01-16 12:20:33 read UDP: Unknown error (code=10054)
```

**Comment by cenk1cenk2** [comment]
Hey @malikshi ,

Unfortunately no, I have not touched the configuration of SoftEther except for Dockerizing it in almost 7 years.

Where is this error coming from, is it from the client or the server?

Could be related to the changes due to the WireGuard or something else?

**Comment by malikshi** [comment]
I think the edge version several command been replaced by new one like this one
VPN Command Line Management Utility:
**PortsUDPSet**: This command can be used to specify a single or multiple UDP ports the server should listen on. 0 can be specified to disable the UDP listener.
Administrator privileges are required to execute the command.
**PortsUDPGet**: This command can be used to retrieve the UDP ports the server is listening on.
The two commands replace the functionality that was previously provided by `OpenVpnEnable` and `OpenVpnGet`, respectively.

You can check the details on vpncmd.

**Comment by cenk1cenk2** [comment]
Oh okay, but how about the config file can that be in any way migrated to the new version. Because we do not really use the `vpncmd` directly too much, just to start the server, etc. I have gone through the issues a bit and there is no real documentation out for it yet as well as the Admin Management Interface is not adapted yet.
