### ISSUE TITLE
How to adding users at runtime ?

### ISSUE THREAD

**Issue by elico** [cenk1cenk2/docker-softether-vpnsrv#19]
Hey,

Since I don't have a lot of experience with softether-vpn I do not know how to add users at run time.
I mainly wan to use it for l2tp and sstp connection.

Thanks,

**Comment by cenk1cenk2** [comment]
Hey,
You can just download the softether's gui softhether vpn server manager from their site, connect to the server and add users. Be sure to use the persistent volume for the configuration file.
