### ISSUE TITLE
OpenVPN clone function not working

### ISSUE THREAD

**Issue by dormancygrace** [cenk1cenk2/docker-softether-vpnsrv#22]
Me, again =) Have you tried ovpn clone function? it doesn't work in this container.  Even can't save port #. And there is some differences in config for v4 and v5 server

**Comment by dormancygrace** [comment]
upd: tcp connection works, udp not working

**Comment by malikshi** [comment]
e.g
Add UDP port
`PortsUDPSet "1194"`
Enabled OpenVPN
`ProtoOptionsSet OpenVPN /NAME:Enabled /VALUE:true`
Generate config
`OpenVpnMakeConfig ovpn.zip`

**Comment by dormancygrace** [comment]
Sorry for asking, but can you give me server .config file? For now I have very limited access to container

**Comment by malikshi** [comment]
> Sorry for asking, but can you give me server .config file? For now I have very limited access to container

Sorry i can't provided the config.

**Comment by dormancygrace** [comment]
`PortsUDPSet "1194"` solved problem, thanks!
