### ISSUE TITLE
no arm64 builds 

### ISSUE THREAD

**Issue by dormancygrace** [cenk1cenk2/docker-softether-vpnsrv#28]
What happend with arm64 build?

**Comment by cenk1cenk2** [comment]
Sorry I seem to have a rogue branch triggering some old pipeline, I would look in to it but it would temporarily be fixed after this build finishes.

https://gitlab.kilic.dev/docker/softether-vpnsrv/-/pipelines/21406

**Comment by dormancygrace** [comment]
Thanks
