### ISSUE TITLE
2 local bridge interface create

### ISSUE THREAD

**Issue by ilyamen** [cenk1cenk2/docker-softether-vpnsrv#37]
hello, how can I create two vpn hubs with dnsmasq and run the network interface for example name "soft1" at the same time

**Comment by ilyamen** [comment]
I created 2 hubs and made 2 local bridges for it, duplicated the settings in the dnsmasq configuration file and edited them for 2 interfaces. after restarting the container, I executed "ip address add 10.8.0.1/24 dev tap_soft1" now devices can connect and get ip. But I don't have Internet access, I'm trying to figure out why. Are there any other actions that need to be performed?

**Comment by cenk1cenk2** [comment]
[This is the last part.](https://github.com/cenk1cenk2/docker-softether-vpnsrv/blob/master/pipe/tasks.go#L80)

This is not very sustainable in the sense that I suppose it would be gone whenever the container is restarted,
but maybe we can add post scripts where it executes your scripts after the default setup has run and just before services start like many other containers.

Please inform me further if this is working and adding something like this would be a good solution for you too.

**Comment by cenk1cenk2** [comment]
Cool we can add a mechanism to execute user scripts as hooks at the right time. So this should just be before the starting of the services and after the confoguration has finished.

I will add it and inform you back but it might take a while since currently I am mostly swamped.

**Comment by cenk1cenk2** [comment]
Please check out the brief description on [hooks](https://github.com/cenk1cenk2/docker-softether-vpnsrv#hooks) where you can add your script as an executable to a certain location to fire whenever the appropriate time comes. Here you can add the manual commands you did to get it working so that it would fire every time the container starts.
