### ISSUE TITLE
Enable VPN Gate plugin

### ISSUE THREAD

**Issue by lonnietc** [cenk1cenk2/docker-softether-vpnsrv#7]
Hello,

I am experimenting with, and learning about SoftEther.

With your wonderful docker-compose script, I have been able to set up a SoftEther Server on one of my servers for testing and would now like to test being able to "enable" the server to join the SoftEther VPN Gate project.

https://www.vpngate.net/en/join.aspx

I started the windows VPN server manager and connected to the SoftEther VPN server container without any problems, but do not see the "VPN Gate Setting" button and have tried different vpnmgr.exe releases to see if was something there, but they all seem the same and do not show it.

I have to assume that there is some SoftEther flag that needs to be enabled in order to load that plugin option, but not completely sure on this.

Any ideas?
Thanks in advance.

**Comment by cenk1cenk2** [comment]
I actually have no idea about this, pretty sorry for the late reply, since I was not subscribed to this repo somehow.

**Comment by cenk1cenk2** [comment]
If you have figured this out since considarable time passed please tell me so that we can enable that feature.
